platform:
  - x86
#  - x64

install:
  - ps: Write-Output $env:Platform
  - ps: Write-Output $env:APPVEYOR_REPO_COMMIT_MESSAGE
  - ps: if($env:APPVEYOR_REPO_COMMIT_MESSAGE.ToLower().Contains('[publish binary]')) { ECHO "publish!" }
  - ECHO %PLATFORM%
  - ECHO "%APPVEYOR_REPO_COMMIT_MESSAGE%"
  - if not "%APPVEYOR_REPO_COMMIT_MESSAGE%" == "%APPVEYOR_REPO_COMMIT_MESSAGE:[publish binary]=%" (ECHO "FOUND") ELSE (ECHO "NOT FOUND")

build: OFF
test: OFF
deploy: OFF

